
// This file has been generated by the GUI designer. Do not modify.
namespace Amoeba
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action CoreAction;
		
		private global::Gtk.Action CacheAction;
		
		private global::Gtk.Action ToolsAction;
		
		private global::Gtk.Action LanguagesAction;
		
		private global::Gtk.Action HelpAction;
		
		private global::Gtk.Action ConnectStartAction;
		
		private global::Gtk.Action ConnectStopAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Amoeba.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.CoreAction = new global::Gtk.Action ("CoreAction", global::Mono.Unix.Catalog.GetString ("Core"), null, null);
			this.CoreAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Core");
			w1.Add (this.CoreAction, null);
			this.CacheAction = new global::Gtk.Action ("CacheAction", global::Mono.Unix.Catalog.GetString ("Cache"), null, null);
			this.CacheAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cache");
			w1.Add (this.CacheAction, null);
			this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
			this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
			w1.Add (this.ToolsAction, null);
			this.LanguagesAction = new global::Gtk.Action ("LanguagesAction", global::Mono.Unix.Catalog.GetString ("Languages"), null, null);
			this.LanguagesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Languages");
			w1.Add (this.LanguagesAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.ConnectStartAction = new global::Gtk.Action ("ConnectStartAction", global::Mono.Unix.Catalog.GetString ("Connect Start"), null, null);
			this.ConnectStartAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Connect Start");
			w1.Add (this.ConnectStartAction, null);
			this.ConnectStopAction = new global::Gtk.Action ("ConnectStopAction", global::Mono.Unix.Catalog.GetString ("Connect Stop"), null, null);
			this.ConnectStopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Connect Stop");
			w1.Add (this.ConnectStopAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Amoeba.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Amoeba.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='CoreAction' action='CoreAction'><menuitem name='ConnectStartAction' action='ConnectStartAction'/><menuitem name='ConnectStopAction' action='ConnectStopAction'/></menu><menu name='CacheAction' action='CacheAction'/><menu name='ToolsAction' action='ToolsAction'/><menu name='LanguagesAction' action='LanguagesAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Notebook tab
			global::Gtk.Label w3 = new global::Gtk.Label ();
			w3.Visible = true;
			this.notebook1.Add (w3);
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Information");
			this.notebook1.SetTabLabel (w3, this.label1);
			this.label1.ShowAll ();
			// Notebook tab
			global::Gtk.Label w4 = new global::Gtk.Label ();
			w4.Visible = true;
			this.notebook1.Add (w4);
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Search");
			this.notebook1.SetTabLabel (w4, this.label2);
			this.label2.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w5.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
			this.hbox1.Add (this.label6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label6]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
			this.hbox1.Add (this.label9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label9]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
			this.label8.Justify = ((global::Gtk.Justification)(1));
			this.hbox1.Add (this.label8);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label8]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
			this.label7.Justify = ((global::Gtk.Justification)(1));
			this.hbox1.Add (this.label7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label7]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 4;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1003;
			this.DefaultHeight = 498;
			this.Show ();
		}
	}
}
