
// This file has been generated by the GUI designer. Do not modify.
namespace Amoeba
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action CoreAction;
		
		private global::Gtk.Action CacheAction;
		
		private global::Gtk.Action ToolsAction;
		
		private global::Gtk.Action LanguagesAction;
		
		private global::Gtk.Action HelpAction;
		
		private global::Gtk.Action ConnectStartAction;
		
		private global::Gtk.Action ConnectStopAction;
		
		private global::Gtk.VBox vbox;
		
		private global::Gtk.MenuBar _menubar;
		
		private global::Gtk.Notebook notebook;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Amoeba.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Menu");
			this.CoreAction = new global::Gtk.Action ("CoreAction", global::Mono.Unix.Catalog.GetString ("Core"), null, null);
			this.CoreAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Core");
			w1.Add (this.CoreAction, null);
			this.CacheAction = new global::Gtk.Action ("CacheAction", global::Mono.Unix.Catalog.GetString ("Cache"), null, null);
			this.CacheAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cache");
			w1.Add (this.CacheAction, null);
			this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
			this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
			w1.Add (this.ToolsAction, null);
			this.LanguagesAction = new global::Gtk.Action ("LanguagesAction", global::Mono.Unix.Catalog.GetString ("Languages"), null, null);
			this.LanguagesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Languages");
			w1.Add (this.LanguagesAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.ConnectStartAction = new global::Gtk.Action ("ConnectStartAction", global::Mono.Unix.Catalog.GetString ("Connect Start"), null, null);
			this.ConnectStartAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Connect Start");
			w1.Add (this.ConnectStartAction, null);
			this.ConnectStopAction = new global::Gtk.Action ("ConnectStopAction", global::Mono.Unix.Catalog.GetString ("Connect Stop"), null, null);
			this.ConnectStopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Connect Stop");
			w1.Add (this.ConnectStopAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Amoeba.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Amoeba.Icons.Amoeba.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Amoeba.MainWindow.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			// Container child vbox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='_menubar'><menu name='CoreAction' action='CoreAction'><menuitem name='ConnectStartAction' action='ConnectStartAction'/><menuitem name='ConnectStopAction' action='ConnectStopAction'/></menu><menu name='CacheAction' action='CacheAction'/><menu name='LanguagesAction' action='LanguagesAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
			this._menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/_menubar")));
			this._menubar.Name = "_menubar";
			this.vbox.Add (this._menubar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox [this._menubar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.notebook = new global::Gtk.Notebook ();
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 0;
			// Notebook tab
			global::Gtk.Label w3 = new global::Gtk.Label ();
			w3.Visible = true;
			this.notebook.Add (w3);
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Information");
			this.notebook.SetTabLabel (w3, this.label1);
			this.label1.ShowAll ();
			// Notebook tab
			global::Gtk.Label w4 = new global::Gtk.Label ();
			w4.Visible = true;
			this.notebook.Add (w4);
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Search");
			this.notebook.SetTabLabel (w4, this.label2);
			this.label2.ShowAll ();
			this.vbox.Add (this.notebook);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox [this.notebook]));
			w5.Position = 1;
			this.Add (this.vbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1003;
			this.DefaultHeight = 498;
			this.Show ();
		}
	}
}
